### ISSUE TITLE
Displaying permission settings  dialog continuously when location permission is not added in manifest 

### ISSUE THREAD

**Issue by pranaypatel512** [BirjuVachhani/locus-android#19]
@BirjuVachhani 
I am using this lib in my app, and just came across with one found issue. If I haven't declare Location permission in manifest ( which is require for lib) the lib will display settings dialog for permission continuously. Can you please check and resolved it.

Thanks you for the wonderful lib.
Steps To reproduce:
-> Try to run access location using your lib without adding location permission in app manifest.

**Comment by BirjuVachhani** [comment]
@pranaypatel512 Thanks for reporting this issue. It'll be resolved soon!

**Comment by BirjuVachhani** [comment]
Fixed in release 2.1.0
https://github.com/BirjuVachhani/locus-android/releases/tag/2.1.0

Thank you @pranaypatel512 for your contribution to this library. Finding bugs and fixing them means a lot to me and you helped me to improve this library by reporting them. Thanks again!
