### ISSUE TITLE
Require functionality of change message text for update rational and permanently deny permissions.

### ISSUE THREAD

**Issue by sagarkacha** [BirjuVachhani/locus-android#26]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3ABirjuVachhani
    
### Description

Required access to change message of change message text for update rational and permanently deny permissions.

### Steps to Reproduce

1. Request permission and press deny button on permission dialog.
2. It will show dialog and required feature to change dialog text.

**Expected behavior:** Message text change.

**Actual behavior:** Message text not changing.

**Reproduces how often:** Request permission and press deny button on permission dialog.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by BirjuVachhani** [comment]
Will be fixed in the next release 3.0.0-alpha05

**Comment by sagarkacha** [comment]
One more issue I just got. Location permission dialog is not getting dismissed when I press any actions and also permanently deny location dialog also not comes up.
