### ISSUE TITLE
How to increase time interval in location update?

### ISSUE THREAD

**Issue by EleshBaraiya** [BirjuVachhani/locus-android#38]
### How to add time interval

    Locus.startLocationUpdates(this) { result ->
            result.location?.let(::onLocationUpdate)
            result.error?.let(::onError)
        }

**Comment by BirjuVachhani** [comment]
@EleshBaraiya 
You can checkout wiki: [Here](https://github.com/BirjuVachhani/locus-android/wiki/Customizations)

```kotlin
Locus.configure {
    request {
        fastestInterval = 1000
        priority = LocationRequest.PRIORITY_HIGH_ACCURACY
        interval = 1000
        maxWaitTime = 2000
    }
}
```

**Comment by BirjuVachhani** [comment]
I think this answers your question. I'm closing this issue for now. Please create a new issue it if it doesn't work for you.
