### ISSUE TITLE
Some help needed

### ISSUE THREAD

**Issue by nicemak** [BirjuVachhani/locus-android#41]
Thanks for the great library.

My questions are:

1- How to get location if internet (wifi / mobile data) is off, GPS only?
2- If GPS is off how can we turn on location programmatically? Can you put this feature in your library?

Thank you once again for this library.

**Comment by BirjuVachhani** [comment]
1. It uses `FusedLocationProviderClient` which tries to get location best way possible by using GPS and internet. So you don't need to worry about it much. I believe if `FusedLocationProviderClient` can't give you location, then none can.

2. Yes, it supports feature to ask user to enable location. It is enabled by default, so when your location is disabled, it should automatically ask to enable it. `shouldResolveRequest` is responsible for that. You can change default behaviour by providing your custom configuration. 

Checkout [Wiki](https://github.com/BirjuVachhani/locus-android/wiki) for more information.

**Comment by nicemak** [comment]
I am using this library in foreground service, if application is killed, my service is running, but if user turn off location, it doesn't ask to enable it, it only asked when application is open and in foreground.

**Comment by BirjuVachhani** [comment]
@nicemak Well, I think there is no way of knowing when user disables the location, not that I know of. If you know then you can share here. I'll definitely look into it.
