### ISSUE TITLE
Not receiving location updates while screen is off

### ISSUE THREAD

**Issue by nicemak** [BirjuVachhani/locus-android#44]
**Describe the bug**
Hi, i use your library in a foreground service, when device is unlocked it gets location updates, but when device is locked it doesn't get location update, can you please help me with this?

**Expected behavior**
should receive location updates when device is locked.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 9 Pro
 - OS: Android
 - Version 10

**Comment by BirjuVachhani** [comment]
@nicemak Are you requesting background location permission?

**Comment by nicemak** [comment]
yes i am doing that

`<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />`

**Comment by nicemak** [comment]
and one thing i also noted that 

`Locus.getCurrentLocation(context)`

always return same location.

**Comment by BirjuVachhani** [comment]
> and one thing i also noted that
> 
> `Locus.getCurrentLocation(context)`
> 
> always return same location.

That's because it is supposed to return most recent location. Use that only if you want a single update.

**Comment by BirjuVachhani** [comment]
@nicemak You have to enable background location in Locus. Try this:

```kotlin
Locus.configure {
    enableBackgroundUpdates = true // default: false
}
```

**Comment by nicemak** [comment]
I am already doing it

**Comment by BirjuVachhani** [comment]
Then, There's only one option left. This has to be happing because of doze mode. This has nothing to do with this library but Android OS itself. I think you have to use foreground service, Disabling battery saver for the same might be useful.

**Comment by nicemak** [comment]
I am using foreground service, device doesn't enter in doze mode when u turn off screen, it takes time to enter in doze mode may be 10 or 15 mints, i am requesting locations after 5 seconds interval, when device is unlocked and i am on desktop, no visible application but my foreground service is running in background, system doesn't kill my service. the issue when device screen is off by pressing power button or screen time out, locations stops, when i turn on screen and doesn't unlocked my device locations back, i also tried with a timer to log on every 5 seconds logs are showing on console but locations are not.

**Comment by nicemak** [comment]
> > and one thing i also noted that
> > `Locus.getCurrentLocation(context)`
> > always return same location.
> 
> That's because it is supposed to return most recent location. Use that only if you want a single update.

yes most recent location, but same coordinates are return, as u know that GPS jitters, location is same but some values are different in lat lng.

**Comment by BirjuVachhani** [comment]
Interesting...are you allowing location. Permission all the time or for this time only?

And have you tested the same in lesser android versions like Android 9 and Android 7?

**Comment by nicemak** [comment]
> Interesting...are you allowing location. Permission all the time or for this time only?
> 
> And have you tested the same in lesser android versions like Android 9 and Android 7?

Yes i am allowing all the time.

yes i tested with marsh mellow.

**Comment by BirjuVachhani** [comment]
And? Did it work with marsh mellow?
