### ISSUE TITLE
Move dialog texts from configuration to string.xml

### ISSUE THREAD

**Issue by kosratdev** [BirjuVachhani/locus-android#45]
**Is your feature request related to a problem? Please describe.**
Improve text messages in the dialogs to be easily translatable without any efforts.

**Describe the solution you'd like**
Move the text messages in the configuration to `string.xml` file and then anyone can override and translate them easily just by adding the text keys to their `strings.xml` files.

**Comment by BirjuVachhani** [comment]
@kosratdev 

Fixed in `3.2.0`

```groovy
implementation 'com.github.BirjuVachhani:locus-android:3.2.0'
```

Check migration guide in [README.md](https://github.com/BirjuVachhani/locus-android/blob/master/README.md)
