### ISSUE TITLE
location_settings_denied returned while enabling the location.

### ISSUE THREAD

**Issue by kosratdev** [BirjuVachhani/locus-android#46]
**Describe the bug**
When the device's location is turned off then the app requests to enable location after you enable it, it will return `location_settings_denied`  

**To Reproduce**
1. Turn off your locatoin.
2. Go to your app that uses this library.
2. Request to get `Locus.getCurrentLocation`
3. Enable location

**Expected behavior**
After enabling the location should retry to get the location instead returning `location_settings_denied`

**Smartphone (please complete the following information):**
 - Device: Samsung A70
 - OS: Android
 - Version: Android 11

**Comment by BirjuVachhani** [comment]
@kosratdev It is supposed to retrieve location updates. `location_settings_denied` is thrown if it could verify that the location is enabled.

**Comment by kosratdev** [comment]
@BirjuVachhani The library requests to open the device's location when enabled from the library dialog it returns `location_settings_denied`

**Comment by BirjuVachhani** [comment]
@kosratdev That's correct but it should only return that if something is not right. Could you please verify this on Android devices other than Samsung because I tried to replicate the same on the emulator but it worked fine. Maybe that will be helpful to narrow down the issue to specific devices/OS.

**Comment by kosratdev** [comment]
Just I have checked it, it works for the emulator but on my Samsung device doesn't work I don't know why.
I will try to test it on another physical device

**Comment by BirjuVachhani** [comment]
@kosratdev I thought that might be the case. I do not own any Samsung devices but I would love to get some more info on this. Maybe you could share the stacktrace/logs for this from the Samsung device? Also, there might be chances that this may work just fine for some Samsung devices. So if you have any other around, please test on them as well.

**Comment by Damercy** [comment]
Hey, I'm facing the same issue as well. When I use `getCurrentLocation()` and have my location turned off, it requests for turning on the location as expected, however, once I do turn on the location, it fails with exception in log `com.google.android.gms.common.api.ResolvableApiException: 6: RESOLUTION_REQUIRED` i.e. It is unable to resolve that I have actually granted the location & hence start getting the current location. Ideally, once I turn on the location, it should proceed forward with giving me the current location automatically instead of throwing above exception. Testing device is a Lenovo K10 Note running Android Pie.

Any help is appreciated! 😄

**Comment by BirjuVachhani** [comment]
This seems weird. Everything seems to be working fine when I test it on an emulator. Will try to check with a real device.

**Comment by iballan** [comment]
Any update about this issue ?

**Comment by BirjuVachhani** [comment]
I tested it on Samsung S20 (Android 11) on Browser stack and it seems to be working fine. Can anyone provide me a video or anything like that?

**Comment by ankush-dhiman** [comment]
I was facing same issue, So I made some changes in library. Now It is working fine for me.
Tested (Eabled/Disabled GPS and Handled it based on resut code.

  override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == REQUEST_CODE_LOCATION_SETTINGS) {
            if (resultCode == RESULT_OK) {
                shouldProceedForLocation()
            }
            else {
                checkSettings(success = { shouldProceedForLocation() }) {
                    postResult(Constants.LOCATION_SETTINGS_DENIED)
                }
            }

**Comment by BirjuVachhani** [comment]
> I was facing same issue, So I made some changes in library. Now It is working fine for me.
> Tested (Eabled/Disabled GPS and Handled it based on resultCode.
> 
> ```
>   override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
>         super.onActivityResult(requestCode, resultCode, data)
>         if (requestCode == REQUEST_CODE_LOCATION_SETTINGS) {
>             if (resultCode == RESULT_OK) {
>                 shouldProceedForLocation()
>             }
>             else {
>                 checkSettings(success = { shouldProceedForLocation() }) {
>                     postResult(Constants.LOCATION_SETTINGS_DENIED)
>                 }
>             }
> ```

If this is working for everyone then I'll make required changes and publish a new version.

**Comment by BirjuVachhani** [comment]
Can anyone check on this dependency this and confirm here? I have applied @ankush-dhiman's solution on this. If this works then I'll release a version.

```
implementation 'com.github.BirjuVachhani:locus-android:master-SNAPSHOT'
```

**Comment by BirjuVachhani** [comment]
@kosratdev Did you get a chance to check this?
