### ISSUE TITLE
How to resolve this

### ISSUE THREAD

**Issue by UvrajSB** [BirjuVachhani/locus-android#69]
![image](https://user-images.githubusercontent.com/73571511/195774056-a9028e36-b94b-4ff3-970d-26a53a9dd96b.png)

**Comment by BirjuVachhani** [comment]
Can you show me your app dependencies?

**Comment by UvrajSB** [comment]
![image](https://user-images.githubusercontent.com/73571511/195910462-42964c42-02e9-4516-8d6a-6e5492a28a86.png)

**Comment by BirjuVachhani** [comment]
Did you try using the latest version of locus which is v4.1.0?

**Comment by UvrajSB** [comment]
Yes, that too is not working. Just checked

**Comment by BirjuVachhani** [comment]
Then it is your project specific issue because it works for others. Not sure but smells like a split apk issue! Are you splitting apk? Can try turning off splitting?

**Comment by kustraslawomir** [comment]
Same issue here:

    Process: com.staging.ultron.ar, PID: 10588
    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~Wfp6PaY6NL9uybfQW_nv3w==/com.staging.ultron.ar-E3MVL-MbZ3lXMKZodng6_g==/base.apk!classes2.dex)

**Comment by kustraslawomir** [comment]
implementation "com.google.android.gms:play-services-location:21.0.1"
    implementation 'com.github.BirjuVachhani:locus-android:4.1.0'

**Comment by UvrajSB** [comment]
@kustraslawomir Thank you so much
It worked!
