### ISSUE TITLE
Request enable location crash

### ISSUE THREAD

**Issue by kosratdev** [BirjuVachhani/locus-android#83]
**Describe the bug**
The second request to enable location will make a crash if the first has been canceled.

**To Reproduce**
1. Go to device settings and turn off the location. 
2. Open the locus sample app.
3. Enable resolve location settings. 
4. Start getting location 
5. The app asks to enable location service.
6. Cancel the request
7. Press the start button again 
8. Crash 💥 

**Expected behavior**
I'm expecting to request to enable the location again. 

**Screenshots**
<img width="1274" alt="Screenshot 2023-05-18 at 16 03 03" src="https://github.com/BirjuVachhani/locus-android/assets/10336475/dc69a60b-3a06-4a92-af50-da487c2a0698">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Emulator 
 - OS: Android API 33
 - Version 4.1.1

**Additional context**

**Comment by kosratdev** [comment]
Hi @BirjuVachhani, I have fixed this issue in PR #84. Please check it.

**Comment by BirjuVachhani** [comment]
Fixed in `v4.1.2`
