### ISSUE TITLE
Custom dialog designs.

### ISSUE THREAD

**Issue by Sypers** [BirjuVachhani/locus-android#92]
**Is your feature request related to a problem? Please describe.**
The existing dialogs suffer from being incompatible with some designs like Material 3. and not being able to change colors, fonts, etc.

**Describe the solution you'd like**
it would be helpful if the dialogs design could be customized or disabled and replaced with a custom implementation.

**Describe alternatives you've considered**
Handle location permission check dialogs before calling Locus for location.

**Additional context**
None.

**Comment by BirjuVachhani** [comment]
Hi @Sypers, Locus does support custom text and colors for those dialogs. See [wiki](https://github.com/BirjuVachhani/locus-android/wiki#now) for more info. As for the colors, you can use standard color resource identifiers same as any other dialog to override colors.

As for Material 3, Locus uses old material design. I moved away from Android development 3 years ago and I am not up to date with current situation. I'll see if I can get it updated to material 3. Feel free to drop a PR for this.

**Comment by Sypers** [comment]
Hello. Thanks for your response. I'm currently working on a personal project so i don't think i will be sending any PRs' soon. But thanks for the info.
